name: Pyinstaller Make Directory
run-name: ${{ github.actor }} is testing out Pyinstaller Actions

on:
  push:
    paths:
      - '.github/workflows/pyinstaller_mkdir.yaml'  # このファイルの変更時にトリガー
      - 'src/read_mypackage.py'                    # 関連するコード変更も許可

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: make directory
        shell: cmd
        run: |
            mkdir dist\test-dir
            echo. > dist\test-dir\empty.txt

        # Artifactに出力
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ${{ runner.os }} Read External Image
            path: dist
            compression-level: 9 # maximum compression
            include-hidden-files: true