name: Pyinstaller Actions Read Package and toml
run-name: ${{ github.actor }} is testing  Read Package and toml

on:
  push:
    paths:
      - '.github/workflows/pyinstaller_read_package_toml.yaml'  # このファイルの変更時にトリガー
      - 'src/read_package_toml.py'                    # 関連するコード変更も許可
      - 'read_package_toml.spec'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-plugin-export

        # pyproject.tomlのうち必要なライブラリのみをrequirements_pyproject.tomlに変換する
      - name: Create requirements_pyproject.txt from pyproject.toml
        run: |
          poetry export -f requirements.txt --output requirements_pyproject.txt --without-hashes

        # コードの実行に必要なパッケージのインストール
      - name: Install Dependencies
        run: |
          cat requirements_pyproject.txt
          pip install -r requirements_pyproject.txt --trusted-host pypi.org

        # コードをexe化
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
            python_ver: '3.10'
            spec: 'read_package_toml.spec'                  # specファイルか、pythonファイルを指定可能
            exe_path: './dist'
            upload_exe_with_name: 'read package toml'       # artifact(zipファイル)名