name: Pyinstaller Actions Read toml
run-name: ${{ github.actor }} is testing  Read toml

on:
  push:
    paths:
      - '.github/workflows/pyinstaller_read_toml_onefile.yaml'  # このファイルの変更時にトリガー
      - 'src/read_toml.py'                    # 関連するコード変更も許可

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

        # ここを改良
      - name: Build Executable
        uses: sayyid5416/pyinstaller@v1
        with:
            python_ver: '3.10'
            spec: 'spec/read_toml.spec'                     # specファイルか、pythonファイルを指定可能
            exe_path: './dist'
            upload_exe_with_name: 'read toml'               # artifact名